export const CONTRACT_LIST_REQUEST = 'CONTRACT_LIST_REQUEST'
export const CONTRACT_LIST_SUCCESS = 'CONTRACT_LIST_SUCCESS'
export const CONTRACT_LIST_FAIL = 'CONTRACT_LIST_FAIL'

export const CONTRACT_DETAILS_REQUEST = 'CONTRACT_DETAILS_REQUEST'
export const CONTRACT_DETAILS_SUCCESS = 'CONTRACT_DETAILS_SUCCESS'
export const CONTRACT_DETAILS_FAIL = 'CONTRACT_DETAILS_FAIL'

export const CONTRACT_ENTRY_REQUEST = 'CONTRACT_ENTRY_REQUEST'
export const CONTRACT_ENTRY_SUCCESS = 'CONTRACT_ENTRY_SUCCESS'
export const CONTRACT_ENTRY_FAIL = 'CONTRACT_ENTRY_FAIL'
export const CONTRACT_ENTRY_RESET = 'CONTRACT_ENTRY_RESET'

export const CONTRACT_DELETE_REQUEST = 'CONTRACT_DELETE_REQUEST'
export const CONTRACT_DELETE_SUCCESS = 'CONTRACT_DELETE_SUCCESS'
export const CONTRACT_DELETE_FAIL = 'CONTRACT_DELETE_FAIL'

export const CONTRACT_UPDATE_REQUEST = 'CONTRACT_UPDATE_REQUEST'
export const CONTRACT_UPDATE_SUCCESS = 'CONTRACT_UPDATE_SUCCESS'
export const CONTRACT_UPDATE_FAIL = 'CONTRACT_UPDATE_FAIL'
