export const SERVICEFEES_LIST_REQUEST = 'SERVICEFEES_LIST_REQUEST'
export const SERVICEFEES_LIST_SUCCESS = 'SERVICEFEES_LIST_SUCCESS'
export const SERVICEFEES_LIST_FAIL = 'SERVICEFEES_LIST_FAIL'

export const SERVICEFEES_ENTRY_REQUEST = 'SERVICEFEES_ENTRY_REQUEST'
export const SERVICEFEES_ENTRY_SUCCESS = 'SERVICEFEES_ENTRY_SUCCESS'
export const SERVICEFEES_ENTRY_FAIL = 'SERVICEFEES_ENTRY_FAIL'
export const SERVICEFEES_ENTRY_RESET = 'SERVICEFEES_ENTRY_RESET'

export const SERVICEFEES_GET_REQUEST = 'SERVICEFEES_GET_REQUEST'
export const SERVICEFEES_GET_SUCCESS = 'SERVICEFEES_GET_SUCCESS'
export const SERVICEFEES_GET_FAIL = 'SERVICEFEES_GET_FAIL'
